config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'groups#index'
  get '/users/search', to: 'users#search'
  resources :groups, only:[:new, :edit, :create, :update] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :users, through: :user_groups
  has_many :user_groups, dependent: :destroy
  accepts_nested_attributes_for :users, allow_destroy: true

  validates :name, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_groups, dependent: :destroy
  has_many :messages
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :find_params, only: [:edit, :update]
  def index
    @groups = Group.order(created_at: :asc)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループを作成しました"
    else
      redirect_to new_group_path, alert: " グループ名を入力してください"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'チャットグループが更新されました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def find_params
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @groups = Group.order(created_at: :asc)
    @group = Group.find(params[:group_id])
    @message = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
        format.html
        format.json {
          message_array = []
          @messages.each do |message|
            message_array << {
              body: message.body,
              name: message.user.name,
              image_url: message.image.url,
              created_at: message.created_at.strftime("%Y/%m/%d %H:%M:%S")
            }
          end
          render json: {
            message: message_array
          }
        }
    end
  end

  def create
    @message = Message.new(message_params)
    @message.body = '画像を送信しました。' if message_params[:image] && @message.body.empty?
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path, notice: "メッセージ送信に成功しました"}
        format.json { render json: {
          body: @message.body,
          name: @message.user.name,
          image: @message.image.url,
          created_at: @message.created_at.strftime("%Y/%m/%d %H:%M:%S")
        }
      }
      end
    else
      redirect_to group_messages_path, alert: "メッセージ送信に失敗しました"
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id], user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    name = "%#{params[:keyword]}%"
    @users = User.where('name LIKE ? and not id = ?', name, current_user.id)
    render json: @users
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, placeholder: 'グループ名を入力してください', class: 'chat-group-form__input'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバーを追加", class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = hidden_field_tag 'group[user_ids][]', current_user.id
            %p.chat-group-user__name
              = current_user.name
          - @group.users.each do |user|
            - if(user.id != current_user.id)
              .chat-group-user.clearfix
                = hidden_field_tag 'group[user_ids][]', user.id
                %p.chat-group-user__name
                  = user.name
                = content_tag "a", '削除', class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove", data: { user: { id: user.id }}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", data:{ disable_with: "Save"}, class: "chat-group-form__action-btn"

app/views/groups/index.html.haml
.chat
  .chat-side
    .chat-user
      %h5= current_user.name
      .chat-user__actions
        %a.chat-user__action
        = link_to new_group_path, class: "chat-user__action" do
          %i.fa.fa-pencil-square-o
        = link_to edit_user_registration_path(@users), class: "chat-user__action" do
          %i.fa.fa-cog

    %ul.chat-groups
      - @groups.each do |group|
        %li.chat-group
          = link_to group_messages_path(group),class: 'chat-group__link' do
            %p.chat-group__name= group.name
            %p.chat-group__message= group.name

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for(@group) do |f|
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, 'グループ名', class: 'chat-group-form__label'
      .chat-group-form__field--right
        = f.text_field :name, placeholder: 'グループ名を入力してください', class: 'chat-group-form__input'
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label "チャットメンバーを追加", class: "chat-group-form__label", for: "chat_group_チャットメンバーを追加"
      .chat-group-form__field--right
        .chat-group-form__search.clearfix
          %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          .chat-group-user.clearfix
            = hidden_field_tag 'group[user_ids][]', current_user.id
            %p.chat-group-user__name
              = current_user.name
          - @group.users.each do |user|
            - if(user.id != current_user.id)
              .chat-group-user.clearfix
                = hidden_field_tag 'group[user_ids][]', user.id
                %p.chat-group-user__name
                  = user.name
                = content_tag "a", '削除', class: "user-search-remove chat-group-user__btn chat-group-user__btn--remove", data: { user: { id: user.id }}
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
      .chat-group-form__field--right
        = f.submit "Save", data:{ disable_with: "Save"}, class: "chat-group-form__action-btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - flash.each do |key, value|
      = content_tag(:div, value, class: "flash-message-#{key}")
  = yield

app/views/messages/index.html.haml
.chat
  .chat-side
    .chat-user
      %h5= current_user.name
      .chat-user__actions
        %a.chat-user__action
        = link_to new_group_path, class: "chat-user__action" do
          %i.fa.fa-pencil-square-o
        = link_to edit_user_registration_path(@users), class: "chat-user__action" do
          %i.fa.fa-cog

    %ul.chat-groups
      - @groups.each do |group|
        %li.chat-group
          = link_to group_messages_path(group),class: 'chat-group__link' do
            %p.chat-group__name= group.name
            %p.chat-group__message= group.messages.last.try(:body) || "まだメッセージはありません。"

  .chat-main
    .chat-main-header
      .chat-main-header--left
        %h2 TECH::CAMP
        %p.chat-main-header--left__users
          Members:
          - @group.users.each do |user|
            %span.chat-main-header--left__user
              = user.name
      .chat-main-header--right
        = link_to edit_group_path(@group) do
          .chat-main-header--right__edit-btn Edit


    .chat-main-body
      %ul.chat-main-messages
        - @messages.each do |message|
          %li.chat-main-message
            .chat-main-message__header
              %p.chat-main-message__header__name
                = message.user.name
              %p.chat-main-message__header__time
                = message.created_at.strftime("%Y-%m-%d %H:%M:%S")
            %p.chat-main-message__header__body
              = message.body
              - if message.image.url
                %br = image_tag message.image.url
          %li.chat-main-message

    .chat-main-footer
      = form_for [@group, @message], remote: true do |f|
        .chat-main-footer__body
          = f.text_area :body, row: "1", placeholder: "type a message"
          %label.chat-main-footer__body__file
            = f.file_field :image
            %i.fa.fa-image
        = f.submit "Send", id: "submit", method: :post